SctJSKClient/SctJSKClient/ViewModels/PollResultViewModel.cs
using DTOModel;
using SctJSKClient.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SctJSKClient.ViewModels
{
    public class PollResultViewModel
    {
        public PollResultViewModel()
        {
            Results = new List<Result>();
        }

        public List<Result> Results;
        public Poll Poll { get; set; }
    }
}

SctJSKClient/SctJSKClient/ViewModels/PollViewModel.cs
using DTOModel;
using SctJSKClient.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SctJSKClient.ViewModels
{
    public class PollViewModel
    {

        public PollViewModel()
        {
            Polls = new List<Poll>();
            options = new List<PollOption>();
        }

        public IEnumerable<Poll> Polls { get; set; }
        public IEnumerable<PollOption> options { get; set; }
        public Poll Poll { get; set; }
    }
}

SctJSKClient/SctJSKClient/Controllers/Admin/PollController.cs
using DTOModel;
using GatewayService;
using SctJSKClient.Models;
using SctJSKClient.Security;
using SctJSKClient.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace SctJSKClient.Controllers
{
    [CustomAuthorize(Roles = "Admin,Student,Teacher,HeadMaster")]
    public class PollController : Controller
    {
        private readonly Facade facade = new Facade();

        public ActionResult Index()
        {
            if (SessionPersister.UserRole == "Admin")
            {
                var polls = facade.GetPollService().ReadAll();
                return View(polls);
            }
            else
            {
                var userid = int.Parse(SessionPersister.UserId);
                var polls = facade.GetAnswerService().GetAllUnAnsweredPolls(userid);
                return View(polls);
            }
        }

        public ActionResult GoToPoll(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var poll = facade.GetPollService().Read(id.Value);
            PollOptionViewModel povm = new PollOptionViewModel
            {
                Poll = poll
            };
            return View(povm);
        }

        [HttpPost]
        public ActionResult GoToPoll(PollOptionViewModel povm)
        {

            ModelState.Remove("PollOption");
            ModelState.Remove("Poll.Question");
            if (ModelState.IsValid)
            {
                var userid = int.Parse(SessionPersister.UserId);
                Answer answer = new Answer();
                answer.PollOptionId = int.Parse(povm.selected);
                answer.UserId = userid;
                answer.PollId = povm.Poll.Id;

                HttpResponseMessage response = facade.GetAnswerService().Add(answer);
                if (response.StatusCode == HttpStatusCode.Created)
                    return RedirectToAction("Index");
                else
                    return new HttpStatusCodeResult(response.StatusCode);
            }
            var errors = ModelState.Select(x => x.Value.Errors)
                           .Where(y => y.Count > 0)
                           .ToList();
            var poll = facade.GetPollService().Read(povm.Poll.Id);
            PollOptionViewModel povm2 = new PollOptionViewModel
            {
                Poll = poll
            };
            return View(povm2);

        }

        public ActionResult PollResult(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var pollresults = facade.GetAnswerService().ReadResults(id.Value);
            if (pollresults == null)
            {
                return HttpNotFound();
            }
            List<Result> voteResults = new List<Result>();
            int totalvotes = pollresults.Sum(r => r.Votes);
            foreach (var item in pollresults)
            {
                Result result = new Result();
                result.PollOption = item.OptionText;
                double percent = (double)item.Votes / totalvotes * 100;
                result.VotePercent = Math.Round(percent, 0);
                result.totalvotes = totalvotes;
                result.votes = item.Votes;
                voteResults.Add(result);
            }

            PollResultViewModel prvm = new PollResultViewModel
            {
                Results = voteResults.ToList(),
                Poll = facade.GetPollService().Read(id.Value)
            };
            return View(prvm);
        }

        public ActionResult Create()
        {
            List<PollOption> listpo = new List<PollOption>();
            listpo.Add(new PollOption { OptionText = "" });
            PollViewModel pvm = new PollViewModel
            {
                options = listpo
            };

            return View(pvm);
        }

        public ActionResult BlankPollOptionRow()
        {
            return PartialView("PollOptionRow", new PollOption());
        }

        // POST: Aftale/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PollViewModel pmv)
        {
            if (ModelState.IsValid)
            {
                pmv.Poll.PollOptions = pmv.options.ToList();
                HttpResponseMessage response = facade.GetPollService().Add(pmv.Poll);
                if (response.StatusCode == HttpStatusCode.Created)
                    return Redirect("Index");
                else
                    return new HttpStatusCodeResult(response.StatusCode);
            }
            return View();
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Poll poll = facade.GetPollService().Read(id.Value);
            if (poll == null)
            {
                return HttpNotFound();
            }
            return View(poll);
        }

        // POST: Aftale/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Question,Active")]Poll poll)
        {
            if (ModelState.IsValid)
            {
                HttpResponseMessage response = facade.GetPollService().Update(poll);
                if (response.StatusCode == HttpStatusCode.OK)
                    return RedirectToAction("Index");
                else
                    return new HttpStatusCodeResult(response.StatusCode);
            }
            return RedirectToAction("Index");

        }

        public ActionResult Delete(int id)
        {
            var poll = facade.GetPollService().Read(id);
            facade.GetPollService().Delete(poll);
            return Redirect(Request.UrlReferrer.ToString());
        }

    }
}

SctJSKClient/SctJSKClient/Views/Poll/Create.cshtml
@model SctJSKClient.ViewModels.PollViewModel

@section Scripts{
    <script>
        jQuery.fn.extend({
            live: function (event, callback) {
                if (this.selector) {
                    jQuery(document).on(event, this.selector, callback);
                }
            }
        });

        $('#addItem').click(function () {
            $.ajax({
                url: this.href,
                cache: false,
                success: function (html) {
                    $('#pollOptionRows').append(html);
                }
            });
            return false;
        });

        $('a.deleteRow').live('click', function () {
            $(this).parents('div.pollOptionRow:first').remove();
            return false;
        });

    </script>

}
<style>
    #addItem {
        color: white;
        text-decoration: none;
    }

    #addButton {
        margin-top: 2%;
        margin-left: 2%;
    }
</style>

<div class="container">
    <div class="row">
        <div class="well well-sm">
            <h3><i class="glyphicon glyphicon-tasks"></i> Afstemning</h3>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Poll.Question, new { htmlAttributes = new { @class = "form-control", placeholder = "Spørgsmål" } })
                            @Html.ValidationMessageFor(model => model.Poll.Question, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        
                        <div class="col-md-10">
                            @Html.LabelFor(model => model.Poll.Active)
                            @Html.EditorFor(model => model.Poll.Active, new { htmlAttributes = new { @class = "form-control"} })
                            @Html.ValidationMessageFor(model => model.Poll.Active, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group" style="margin-left:1%;">
                        <div id="pollOptionRows">
                            @foreach (var item in Model.options)
                            {
                                @Html.Partial("PollOptionRow", item);
                            }
                        </div>
                        <button type="button" class="btn btn-primary" id="addButton">
                            @Html.ActionLink("Tilføj", "BlankPollOptionRow", null, new { id = "addItem" })
                        </button>
                    </div>

                </div>
                <div class="row" style="max-width:25%; margin-left: 0%;">
                    <input type="submit" value="Tilføj" class="btn btn-default btn-primary" style="width:100%;" />
                    <a href="@Url.Action("Index", "Poll")" class="btn btn-danger btn-block">Tilbage</a>
                </div>
            }
        </div>
    </div>
</div>

SctJSKClient/SctJSKClient/Views/Poll/Edit.cshtml
@model DTOModel.Poll

@{
    ViewBag.Title = "Edit";
}

<style>
    .prod_title {
        color: #428bca;
        padding: 5px 0 0 15px;
        font-size: 25px;
    }
</style>

<div class="container">
    <div class="row">
        <div class="well well-sm">
            <h3><i class="glyphicon glyphicon-tasks"></i> Afstemning</h3>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <div class="panel panel-default" style="text-align:center;">
                        <p class="prod_title">Redigere sprøgsmål: @Model.Question</p>
                        <div class="clear"></div>
                    </div>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Question, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Question, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.Active)
                                @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    @foreach (var polloption in Model.PollOptions)
                    {
                        @Html.TextBoxFor(m => polloption.OptionText, new { @class = "form-control", placeholder = "Svar" })
                        @Html.ValidationMessageFor(model => polloption.OptionText, "", new { @class = "text-danger" })
                    }


                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Gem" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            }
            </div>
        </div>
    </div>

            <div>
                @Html.ActionLink("Tilabge til listen", "Index")
            </div>

SctJSKClient/SctJSKClient/Views/Poll/GoToPoll.cshtml
@model SctJSKClient.ViewModels.PollOptionViewModel

<div>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h2 class="panel-title" style="text-align:center; font-size:20px;">@Model.Poll.Question</h2>
        </div>
        <div class="panel-body">
            @using (Html.BeginForm())
            {
                @Html.HiddenFor(model => model.Poll.Id)
                @Html.AntiForgeryToken()
                <table class="table table-hover custab" style="background-color:white">
                    @foreach (var poll in Model.Poll.PollOptions)
                {
                        <tr>
                            <td class="prod_title">@poll.OptionText</td>
                            <td> <input type="radio" name="selected" value="@poll.Id" autocomplete="off" /></td>
                        </tr>
                    }
                </table>
                <input type="submit" value="Gem" class="btn btn-primary pull-right" style="width:100%; float: right" />
                <a href="@Url.Action("Index", "Poll")" class="btn btn-danger pull-left">Tilbage</a>
            }
        </div>
    </div>

</div>

SctJSKClient/SctJSKClient/Views/Poll/Index.cshtml
@model IEnumerable<DTOModel.Poll>
@using SctJSKClient.Security

<style>
    .prod_title {
        color: #428bca;
        padding: 5px 0 0 15px;
        font-size: 25px;
    }

    .blockLink {
        display: block;
        padding: 10px;
        background-color: pink; /*maybe not pink, but you get the idea*/
    }

    a.my-class {
        color: #ffffff;
    }

        a.my-class:active {
            color: #ffffff;
        }

        a.my-class:link {
            color: #ffffff;
        }

        a.my-class:visited {
            color: #ffffff;
        }
</style>
@if (SessionPersister.UserRole == "Admin")
{
    <div style="margin-bottom:2%; text-align:center;">
        <a class="btn btn-lg btn-primary " href="/Poll/Create">
            <i class="glyphicon glyphicon-plus pull-left"></i><span>&nbsp;Tilføj afsteming</span>
        </a>
    </div>


    <div class="container">
        <table class="table table-hover custab" style="background-color:white">
            @foreach (var poll in Model)
            {
                <tr>
                    <td class="prod_title"><a href="/Poll/GoToPoll/@poll.Id">@poll.Question</a></td>
                    <td style="font-size:18px">@(poll.Active ? "Aktiv" : "Ikke aktiv")</td>
                    <td>
                        <a class='btn btn-success' href="/Poll/PollResult/@poll.Id"><span class="glyphicon glyphicon-saved"></span> Resultat</a>
                    </td>
                    <td class="text-right">
                        <a class='btn btn-info' href="/Poll/Edit/@poll.Id"><span class="glyphicon glyphicon-info-sign"></span> Redigere</a>
                        <a class='btn btn-danger' href="/Poll/Delete/@poll.Id"><span class="glyphicon glyphicon-remove"></span> Fjern</a>
                        @*<button class="btn btn-danger">
                                  @Html.ActionLink("Slet", "Delete", new { id = poll.Id, @class = "my-class" },
                            new { onclick = "return confirm('Er du sikker på du vil slette denne afstemning?');" })
                                  <span class="glyphicon glyphicon-remove pull-left"></span>

                              </button>*@
                    </td>
                </tr>
            }
        </table>
    </div>
}
else
{
    <div class="panel panel-heading">
        <p style="text-align:center; font-size: 25px; padding: 10px; color:grey">Aktive afstemninger(@Model.Where(p => p.Active == true).Count())</p>
        <div class="clear"></div>
    </div>
    foreach (var poll in Model)
    {
        if (poll.Active == true)
        {
            <a href="/Poll/GoToPoll/@poll.Id">
                <div class="panel panel-default" style="text-align:center; cursor:pointer;">
                    <p class="prod_title">@poll.Question</p>
                    <div class="clear"></div>
                </div>
            </a>
        }

    }
}

SctJSKClient/SctJSKClient/Views/Poll/PollOptionRow.cshtml
@model DTOModel.PollOption

<div class="pollOptionRow">
    @using (Html.BeginCollectionItem("options"))
    {
        <table>
            <tr>
                <td>
                    @Html.TextBoxFor(m => m.OptionText, new { @class = "form-control", placeholder = "Svar" })
                    @Html.ValidationMessageFor(model => model.OptionText, "", new { @class = "text-danger" })
                </td>
                <td>
                    <a href="#" class="deleteRow"><span class="glyphicon glyphicon-remove"></span></a>
                </td>
            </tr>
        </table>
    }
</div>

SctJSKClient/SctJSKClient/Views/Poll/PollResult.cshtml
@model SctJSKClient.ViewModels.PollResultViewModel

@{
    ViewBag.Title = "PollResult";
}
@section scripts{
    <script type="text/javascript">

        function updateProgress(percentage) {
            document.getElementById('ProgressBar').style.width = percentage + "%";
        }
    </script>
}

<div class="panel panel-primary" style="width:100%; margin:20px">
    <div class="panel-heading">
        <h3 class="panel-title">
            Afstemning: @Model.Poll.Question
        </h3>
    </div>

    <div class="panel-body" style="margin:0px; width:100%;">
        <table class="table table-striped">
            @foreach (var item in Model.Results)
            {
                <thead>
                    <tr>
                        <th>Svar</th>
                        <th>Antal stemmer</th>
                        <th>Total antal stemmer: @item.totalvotes</th>
                    </tr>
                </thead>
                <tr>
                    <td>
                        <label>@item.PollOption</label>                        
                    </td>
                    <td>
                        <div>
                            @item.votes
                        </div>
                    </td>
                    <td>
                        <div class="progress">
                            <div id="ProgressBar" class="progress-bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width: @(item.VotePercent+"%")">
                                @item.VotePercent %
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>