SctJSKClient/SctJSKClient/ViewModels/ArrangementViewModel.cs
using DTOModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SctJSKClient.ViewModels
{
    public class ArrangementViewModel
    {
        public ArrangementViewModel()
        {
            ArrangementProducts = new List<ArrangementProduct>();
            Products = new List<Product>();
            Categrories = new List<Category>();
        }

        public Arrangement Arrangement { get; set; }
        public IEnumerable<ArrangementProduct> ArrangementProducts { get; set; }
        public List<Product> Products { get; set; }
        public List<Category> Categrories { get; set; }
        public string[] selected { get; set; }
    }
}

SctJSKClient/SctJSKClient/Controllers/Admin/ArrangementController.cs
using DTOModel;
using GatewayService;
using SctJSKClient.Security;
using SctJSKClient.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace SctJSKClient.Controllers
{
    [CustomAuthorize(Roles = "Admin,HeadMaster")]
    public class ArrangementController : Controller
    {
        Facade facade = new Facade();
        // GET: Arrangement
        public ActionResult Index()
        {
            var arrangements = facade.GetArrangementService().GetAll();
            return View(arrangements);
        }

        public ActionResult GetEvents()
        {
            //Get the events
            var eventList = facade.GetArrangementService().GetEvents();

            //return the events in json
            var rows = eventList.ToArray();
            return Json(rows, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create()
        {
            ArrangementViewModel avm = new ArrangementViewModel()
            {
                Products = facade.GetProductService().GetAll().ToList(),
                Categrories = facade.GetCategoryService().GetAll().ToList()

            };
            return View(avm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ArrangementViewModel avm)
        {
            if (ModelState.IsValid)
            {
                HttpResponseMessage response = facade.GetArrangementService().Add(avm.Arrangement);
                if (response.StatusCode == HttpStatusCode.Created)
                {
                    Arrangement arrangement = response.Content.ReadAsAsync<Arrangement>().Result;
                    foreach (var ap in avm.selected)
                    {
                        ArrangementProduct arp = new ArrangementProduct();
                        arp.ProductId = int.Parse(ap);
                        arp.ArrangementId = arrangement.Id;
                        arp.Quantity = 30;

                        facade.GetArrangementProductService().create(arp);
                    }
                    return RedirectToAction("Index");
                }
                else
                {
                    return new HttpStatusCodeResult(response.StatusCode);
                }

            }
            return View();
        }

        // GET: Aftale/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var arrangement = facade.GetArrangementService().Get(id.Value);
            if (arrangement == null)
            {
                return HttpNotFound();
            }
            return View(arrangement);
        }

        // POST: Aftale/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Arrangement arrangement)
        {

            // TODO: Add delete logic here
            HttpResponseMessage response = facade.GetArrangementService().Delete(arrangement);
            if (response.StatusCode == HttpStatusCode.NoContent)
                return RedirectToAction("Index");
            else
                return new HttpStatusCodeResult(response.StatusCode);

        }


        public ActionResult ViewArrangementDetails(int id)
        {
            ArrangementProductViewModel apvm = new ArrangementProductViewModel();
            apvm.Arrangement = facade.GetArrangementService().Get(id);
            if (apvm.Arrangement == null)
            {
                return HttpNotFound();
            }
            foreach (var item in apvm.Arrangement.Products)
            {
                ArrangementProduct arrangementProduct = new ArrangementProduct();
                arrangementProduct.Quantity = item.Quantity;
                arrangementProduct.Arrangement = apvm.Arrangement;
                arrangementProduct.Product = facade.GetProductService().Get(item.ProductId);

                apvm.ArrangementProducts.Add(arrangementProduct);
            }
            return View(apvm);
        }

    }
}

SctJSKClient/SctJSKClient/Views/Arrangement/Create.cshtml
@model SctJSKClient.ViewModels.ArrangementViewModel
@section Scripts{
    <script>
        $(document).ready(function () {
            var navItems = $('.admin-menu li > a');
            var navListItems = $('.admin-menu li');
            var allWells = $('.admin-content');
            var allWellsExceptFirst = $('.admin-content:not(:first)');

            allWellsExceptFirst.hide();
            navItems.click(function (e) {
                e.preventDefault();
                navListItems.removeClass('active');
                $(this).closest('li').addClass('active');

                allWells.hide();
                var target = $(this).attr('data-target-id');
                $('#' + target).show();
            });
        });
    </script>
}
<style>
    .btn span.glyphicon {
        opacity: 0;
    }

    .btn.active span.glyphicon {
        opacity: 1;
    }
</style>



<div class="container">
    <div class="row">
        <div class="well well-sm">
            <h3><i class="glyphicon glyphicon-tasks"></i> Arrangement</h3>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Arrangement.Title, new { htmlAttributes = new { @class = "form-control", placeholder = "Titel" } })
                            @Html.ValidationMessageFor(model => model.Arrangement.Title, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Arrangement.Description, new { htmlAttributes = new { @class = "form-control", placeholder = "Beskrivelse" } })
                            @Html.ValidationMessageFor(model => model.Arrangement.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">

                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Arrangement.Date, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                            @Html.ValidationMessageFor(model => model.Arrangement.Date, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="container">
                        <div class="row">
                            <div class="col-md-3">
                                <ul class="nav nav-pills nav-stacked admin-menu">
                                    @foreach (var category in Model.Categrories)
                                    {
                                        if (Model.Categrories.First() == category)
                                        {
                                            <li class="active"><a href="" data-target-id="@category.Name"><i class="fa fa-list-alt fa-fw"></i>@category.Name</a></li>
                                        }
                                        else
                                        {
                                            <li><a href="" data-target-id="@category.Name"><i class="fa fa-list-alt fa-fw"></i>@category.Name</a></li>
                                        }

                                    }
                                </ul>
                            </div>
                            @foreach (var category in Model.Categrories)
                            {

                                <div class="col-md-9 well admin-content" id="@category.Name">
                                    <div class="container">
                                        @foreach (var item in Model.Products)
                                        {
                                            if (item.Category.Name == category.Name)
                                            {
                                                <div class="col-xs-6 col-sm-4 col-md-3 col-lg-3" style="margin-bottom: 2%; overflow:auto">
                                                    <div class="thumbnail" style="max-width:150px; float:left; width:100%;">

                                                        <img src="@item.Image" alt="..." style="max-height:100px">
                                                        <a href="#"><h4>@item.Title</h4></a>
                                                        <p>@item.Description</p>

                                                        <hr class="line">
                                                        <div class="wrapper text-left">
                                                            <div class="btn-group" data-toggle="buttons">
                                                                <label class="btn btn-primary">
                                                                    <input type="checkbox" name="selected" value="@item.Id" autocomplete="off" />
                                                                    <span class="glyphicon glyphicon-ok"></span>
                                                                </label>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            }
                                        }
                                    </div>
                                </div>
                            }
                        </div>
                    </div>


                </div>
                <div class="row" style="max-width:25%; margin-left: 0%;">
                    <input type="submit" value="Tilføj" class="btn btn-default btn-primary" style="width:100%;" />
                    <a href="@Url.Action("Index", "Arrangement")" class="btn btn-danger btn-block">Tilbage</a>
                </div>
            }
        </div>
    </div>

</div>

SctJSKClient/SctJSKClient/Views/Arrangement/Delete.cshtml
@model DTOModel.Arrangement

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Arrangement</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SctJSKClient/SctJSKClient/Views/Arrangement/Index.cshtml
<style>
    td.fc-day.fc-past {
        background-color: #EEEEEE;
    }

    .fc-time {
        display: none;
    }
</style>
@section scripts{
    <script src='~/Scripts/locale/da.js'></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#calendar').fullCalendar({
                customButtons: {
                    myCustomButton: {
                        text: 'Tilføj',
                        click: function () {
                            window.location.href = '/Arrangement/Create/';
                        }
                    }
                },
                header: {
                    left: 'prev,next today myCustomButton',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay'
                },
                eventClick: function (calEvent, jsEvent, view) {
                    window.location.href = '/Arrangement/ViewArrangementDetails/' + calEvent.id;
                },
                viewRender: function (view) {
                    var now = new Date();
                    var end = new Date();
                    end.setMonth(now.getMonth() + 1);


                    var cal_date_string = view.start.format('MM') + '/' + view.start.format('YYYY');
                    var cur_date_string = now.getMonth() + '/' + now.getFullYear();
                    var end_date_string = end.getMonth() + '/' + end.getFullYear();

                    if (cal_date_string == cur_date_string) { jQuery('.fc-prev-button').addClass("fc-state-disabled"); }
                    else { jQuery('.fc-prev-button').removeClass("fc-state-disabled"); }

                    if (end_date_string == cal_date_string) { jQuery('.fc-next-button').addClass("fc-state-disabled"); }
                    else { jQuery('.fc-next-button').removeClass("fc-state-disabled"); }
                },
                eventConstraint: {
                    start: moment().format('YYYY-MM-DD'),
                    end: '2100-01-01' // hard coded goodness unfortunately
                },

                theme: false,
                //defaultView: 'agendaDay',
                editable: true,
                events: "/arrangement/getevents/",
                weekends: false,

            });
        });


    </script>
}

<div class="container" style="background-color:white">
    <h1 class="well">Arrangementer</h1>
    <div id="calendar" class="fc-content"></div>
    <hr />
</div>

SctJSKClient/SctJSKClient/Views/Arrangement/ViewArrangementDetails.cshtml
@model SctJSKClient.ViewModels.ArrangementProductViewModel
<script>
    function goBack() {
        window.history.back();
    }
</script>

<div class="container">
    <div class="row">
        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="panel-title">
                    <div class="row">
                        <div class="col-xs-6">
                            <h5><span class="glyphicon glyphicon-tasks"></span>Arrangement: @Model.Arrangement.Title</h5>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <div class="items">
                    <div class="col-md-12">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Produkt</th>
                                    <th>Antal</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var item in Model.ArrangementProducts)
                                {
                                    <tr>
                                        <td class="col-sm-8 col-md-6">
                                            <div class="media">
                                                <a class="thumbnail pull-left" href="/Home/ProductDetails/@item.Product.Id"> <img class="media-object" src="@item.Product.Image" style="width: 72px; height: 72px;"> </a>
                                                <div class="media-body">
                                                    <h4 class="media-heading"><a href="/Home/ProductDetails/@item.Product.Id">@item.Product.Title</a></h4>
                                                    <h5 class="media-heading">@item.Product.Description</h5>
                                                </div>
                                            </div>
                                        </td>
                                        <td data-th="Quantity">
                                            <p class="form-control text-center" style="width:70px;">@item.Quantity</p>
                                        </td>
                                    </tr>
                                            }
                            </tbody>
                        </table>
                    </div>
                    <div class="col-md-12">
                        <div class="panel panel-info">
                            <div class="panel-heading">
                                <h4>Arrangement detaljer</h4>
                            </div>
                            <div class="panel-body">
                                <div>
                                    <h4 style="color:#000000"><b>Beskrivelse</b></h4>
                                    <p>@Model.Arrangement.Description</p>
                                </div>
                                <div>
                                    <h4 style="color:#000000"><b>Dato</b></h4>
                                    <li>
                                        @{
                                            var date = Model.Arrangement.Date.ToString().Split(' ')[0];
                                        }
                                        @date
                                    </li>

                                </div>

                            </div>
                        </div>
                    </div>
                </div>

                <hr>
            </div>

            <div class="panel-footer">
                <div class="row text-center">
                    <div class="col-xs-3">
                        <button onclick="goBack()" class="btn btn-success btn-block"><span class="glyphicon glyphicon-chevron-left"></span>Tilbage</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>