SctJSKClient/SctJSKClient/ViewModels/SaleViewModel.cs
using DTOModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SctJSKClient.ViewModels
{
    public class SaleViewModel
    {
        public SaleViewModel()
        {
            CountOfProducts = new List<ProductCount>();
        }
        public int Total { get; set; } 
        public int TotalProduct { get; set; }
        public List<ProductCount> CountOfProducts { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string MonthDate { get; set; }
        public string FullDate { get; set; }

    }
}

SctJSKClient/SctJSKClient/Controllers/Admin/SaleController.cs
using GatewayService;
using SctJSKClient.Controllers;
using SctJSKClient.Security;
using SctJSKClient.ViewModels;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace SctJSKClient.Controllers
{
    [CustomAuthorize(Roles = "Admin")]
    public class SaleController : Controller
    {
        Facade facade = new Facade();
        // GET: Sale
        public ActionResult Index()
        {
            return View();
        }

        //------------------------------------------------------------------------------------------------------------------
        public ActionResult GetDailySales(SaleViewModel salevm)
        {
            var getDate = salevm.StartDate;
            if (getDate == null || getDate == "")
            {
                DateTime today = DateTime.Today.Date;
                getDate = today.ToString();
            }

            string date = getDate.Split(' ')[0];
            var productCount = facade.GetOrderService().GetOrderedProducts(date);
            int total = productCount.Sum(p => p.TotalPrice);
            int totalproducts = productCount.Sum(p => p.NumberOfProduct);
            SaleViewModel svm = new SaleViewModel
            {
                CountOfProducts = productCount.ToList(),
                Total = total,
                TotalProduct = totalproducts,
                StartDate = date

            };
            return View(svm);
        }

        public JsonResult GetPieRenderer(string date)
        {
            var productCount = facade.GetOrderService().GetOrderedProducts(date);
            var DbResult = productCount.Select(p => new { Title = p.product.Title, Number = p.NumberOfProduct });

            return Json(DbResult, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CharterColumn(string date)
        {
            var productCount = facade.GetOrderService().GetOrderedProducts(date);
            ArrayList xValue = new ArrayList();
            ArrayList yValue = new ArrayList();

            var results = productCount;
            results.ToList().ForEach(rs => xValue.Add(rs.product.Title));
            results.ToList().ForEach(rs => yValue.Add(rs.NumberOfProduct));

            new Chart(width: 390, height: 300, theme: ChartTheme.Blue)
                .AddSeries("Default", chartType: "Column", xValue: xValue, yValues: yValue)
                .Write("bmp");

            return null;
        }

        public ActionResult CharterPie(string date)
        {
            var productCount = facade.GetOrderService().GetOrderedProducts(date);
            ArrayList xValue = new ArrayList();
            ArrayList yValue = new ArrayList();

            var results = productCount;
            results.ToList().ForEach(rs => xValue.Add(rs.product.Title));
            results.ToList().ForEach(rs => yValue.Add(rs.NumberOfProduct));

            new Chart(width: 390, height: 300, theme: ChartTheme.Blue)
                .AddSeries("Default", chartType: "Pie", xValue: xValue, yValues: yValue)
                .Write("bmp");

            return null;
        }
        //------------------------------------------------------------------------------------------------------------------

        public ActionResult GetWeeklySales(SaleViewModel salevm)
        {
            string getFullDate = salevm.FullDate;
            if (getFullDate == null || getFullDate == "")
            {
                DateTime start = DateTime.Today.AddDays(-(int)DateTime.Today.DayOfWeek + (int)DayOfWeek.Monday);
                DateTime end = start.AddDays(4);

                string sd = start.ToString().Split(' ')[0];
                string ed = end.ToString().Split(' ')[0];

                getFullDate = sd + " - " + ed;

            }

            string startDate = getFullDate.Split(' ')[0];
            string endDate = getFullDate.Split(' ')[2];
            //---------------------------------------------------------------
            var productCount = facade.GetOrderService().GetOrderedProductsByDates(startDate, endDate);
            int total = productCount.Sum(p => p.TotalPrice);
            int totalproducts = productCount.Sum(p => p.NumberOfProduct);
            SaleViewModel svm = new SaleViewModel
            {
                CountOfProducts = productCount.ToList(),
                Total = total,
                TotalProduct = totalproducts,
                StartDate = startDate,
                EndDate = endDate,
                FullDate = startDate + " - " + endDate

            };
            return View(svm);
        }

        public ActionResult WeeklyCharterColumn(string startDate, string endDate)
        {
            var productCount = facade.GetOrderService().GetOrderedProductsByDates(startDate, endDate);
            ArrayList xValue = new ArrayList();
            ArrayList yValue = new ArrayList();

            var results = productCount;
            results.ToList().ForEach(rs => xValue.Add(rs.product.Title));
            results.ToList().ForEach(rs => yValue.Add(rs.NumberOfProduct));

            new Chart(width: 390, height: 300, theme: ChartTheme.Blue)
                .AddSeries("Default", chartType: "Column", xValue: xValue, yValues: yValue)
                .Write("bmp");

            return null;
        }

        public ActionResult WeeklyCharterPie(string startDate, string endDate)
        {
            var productCount = facade.GetOrderService().GetOrderedProductsByDates(startDate, endDate);
            ArrayList xValue = new ArrayList();
            ArrayList yValue = new ArrayList();

            var results = productCount;
            results.ToList().ForEach(rs => xValue.Add(rs.product.Title));
            results.ToList().ForEach(rs => yValue.Add(rs.NumberOfProduct));

            new Chart(width: 390, height: 300, theme: ChartTheme.Blue)
                .AddSeries("Default", chartType: "Pie", xValue: xValue, yValues: yValue)
                .Write("bmp");

            return null;
        }

        //------------------------------------------------------------------------------------------------------------------
        public ActionResult GetMonthlySales(SaleViewModel salevm)
        {
            //04/16
            string getDate = salevm.FullDate;

            if (getDate == null || getDate == "")
            {
                DateTime today = DateTime.Now.Date;
                DateTime start = new DateTime(today.Year, today.Month, 1).Date;
                DateTime end = start.AddMonths(1).AddDays(-1);


                string sd = start.ToString().Split(' ')[0];
                string ed = end.ToString().Split(' ')[0];

                getDate = start.ToShortDateString().Split('-')[1] + "-" + start.ToShortDateString().Split('-')[2];
            }
                
            DateTime monthDate = Convert.ToDateTime(getDate.Split(' ')[0]);

            DateTime getStartDate = Convert.ToDateTime(getDate);
            DateTime getEndDate = getStartDate.AddMonths(1).AddDays(-1);

            string startDate = getStartDate.ToString().Split(' ')[0];
            string endDate = getEndDate.ToString().Split(' ')[0];

            int year = int.Parse(getDate.Split('-')[1]);
            int month = monthDate.Month;
            string fullMonthName = new DateTime(year, month, 1).ToString("MMMM", CultureInfo.CreateSpecificCulture("da"));

            //---------------------------------------------------------------
            var productCount = facade.GetOrderService().GetOrderedProductsByDates(startDate, endDate);
            int total = productCount.Sum(p => p.TotalPrice);
            int totalproducts = productCount.Sum(p => p.NumberOfProduct);
            SaleViewModel svm = new SaleViewModel
            {
                CountOfProducts = productCount.ToList(),
                Total = total,
                TotalProduct = totalproducts,
                StartDate = startDate,
                EndDate = endDate,
                MonthDate = year + " - " + FirstLetterToUpper(fullMonthName),
                FullDate = getDate

            };
            return View(svm);
        }

        public string FirstLetterToUpper(string str)
        {
            if (str == null)
                return null;

            if (str.Length > 1)
                return char.ToUpper(str[0]) + str.Substring(1);

            return str.ToUpper();
        }
    }
}

SctJSKClient/SctJSKClient/Views/Sale/GetDailySales.cshtml
@model SctJSKClient.ViewModels.SaleViewModel

@{
    ViewBag.Title = "GetSales";
}
@section scripts{
    <script type="text/javascript">
        $(document).on('focus', '.datepicker', function () {
            $(this).datepicker({ dateFormat: 'dd-mm-yy', beforeShowDay: $.datepicker.noWeekends,closeOnSelect: false });
        });
    </script>
}
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 style="color:#3277b3">Vælg dag</h2>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("GetDailySales", "Sale", FormMethod.Get))
        {
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    @Html.TextBoxFor(m => m.StartDate, new { @class = "datepicker" })
                    <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-folder-open"></span>&nbsp;Se Salg</button>

                </div>
                <div class="col-md-6 col-sm-6">
                    <button type="button" class="btn btn-warning" onclick="location.href='@Url.Action("GetMonthlySales", "Sale")'" style="float:right; overflow:auto"><span class="glyphicon glyphicon-folder-open"></span>&nbsp;Se Månedlige Salg</button>
                    <button type="button" class="btn btn-warning" onclick="location.href='@Url.Action("GetWeeklySales", "Sale")'" style="float:right;  margin-right:1%;"><span class="glyphicon glyphicon-folder-open"></span>&nbsp;Se Ugelige Salg</button>
                </div>
            </div>
        }
        

    </div>
</div>

<div class="panel panel-primary">
    <div class="panel panel-heading" style="text-align:center"><h4 style="color:#ffffff; font-weight:bold">@Model.StartDate</h4></div>

    <div class="form-group">
        <img src="@Url.Action("CharterColumn", new { date = Model.StartDate})" alt="Chart" />
        <img style="float:right" src="@Url.Action("CharterPie", new { date = Model.StartDate})" alt="Chart" />
    </div>

    <table class="table table-hover custab" style="background-color:white">
        <thead>
            <tr>
                <th style="color:#428bca">Produkt</th>
                <th style="color:#428bca">Pris pr. produkt</th>
                <th style="color:#428bca">Total solgt</th>
                <th style="color:#428bca">Samlede indtægter</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.CountOfProducts)
            {
                <tr>
                    <td>@item.product.Title</td>
                    <td>@item.product.Price kr.</td>
                    <td>@item.NumberOfProduct</td>
                    <td>@item.TotalPrice kr.</td>
                </tr>

            }
            <tr>
                <td><b style="color:#3277b3">Total: </b></td>
                <td></td>
                <td><b style="color:#3277b3">@Model.TotalProduct</b></td>
                <td><b style="color:#3277b3">@Model.Total kr.</b></td>
            </tr>
        </tbody>
    </table>

</div>

SctJSKClient/SctJSKClient/Views/Sale/GetMonthlySales.cshtml
@model SctJSKClient.ViewModels.SaleViewModel

@{
    ViewBag.Title = "GetMonthlySales";
}

@section scripts{
    <script type="text/javascript">
        $(function () {
            (".datepicker").datepicker({
                format: "mm-yyyy",
                viewMode: "months",
                minViewMode: "months"
            });
        });
    </script>
}
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 style="color:#3277b3">Vælg måned</h2>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("GetMonthlySales", "Sale", FormMethod.Get))
        {
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <label>Måned: </label>
                    @Html.TextBoxFor(m => m.FullDate, new { @class = "date-picker" })
                    <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-folder-open"></span>&nbsp;Se Salg</button>

                </div>
                <div class="col-md-6 col-sm-6">
                    <button type="button" class="btn btn-warning" onclick="location.href='@Url.Action("GetWeeklySales", "Sale")'" style="float:right; overflow:auto"><span class="glyphicon glyphicon-folder-open"></span>&nbsp;Se Ugelige Salg</button>
                    <button type="button" class="btn btn-warning" onclick="location.href='@Url.Action("GetDailySales", "Sale")'" style="float:right;  margin-right:1%;"><span class="glyphicon glyphicon-folder-open"></span>&nbsp;Se Daglige Salg</button>
                </div>
            </div>
        }

    </div>
</div>

<div class="panel panel-primary">
    <div class="panel panel-heading" style="text-align:center"><h4 style="color:#ffffff; font-weight:bold">@Model.MonthDate</h4></div>

    <div class="form-group">
            <img src="@Url.Action("WeeklyCharterColumn", new { startDate = Model.StartDate, endDate = Model.EndDate })" alt="Chart" />

            <img style="float:right" src="@Url.Action("WeeklyCharterPie", new { startDate = Model.StartDate, endDate = Model.EndDate })" alt="Chart" />
        </div>

    <table class="table table-hover custab" style="background-color:white">
        <thead>
            <tr>
                <th style="color:#428bca">Produkt</th>
                <th style="color:#428bca">Pris pr. produkt</th>
                <th style="color:#428bca">Total solgt</th>
                <th style="color:#428bca">Samlede indtægter</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.CountOfProducts)
            {
                <tr>
                    <td>@item.product.Title</td>
                    <td>@item.product.Price kr.</td>
                    <td>@item.NumberOfProduct</td>
                    <td>@item.TotalPrice kr.</td>
                </tr>

            }
            <tr>
                <td><b style="color:#3277b3">Total: </b></td>
                <td></td>
                <td><b style="color:#3277b3">@Model.TotalProduct</b></td>
                <td><b style="color:#3277b3">@Model.Total kr.</b></td>
            </tr>
        </tbody>
    </table>

</div>

SctJSKClient/SctJSKClient/Views/Sale/GetWeeklySales.cshtml
@model SctJSKClient.ViewModels.SaleViewModel

@{
    ViewBag.Title = "GetWeeklySales";
}

@section scripts{
    <script type="text/javascript">
        $(function () {
            var startDate;
            var endDate;

            var selectCurrentWeek = function () {
                window.setTimeout(function () {
                    $('.week-picker').find('.ui-datepicker-current-day a').addClass('ui-state-active')
                }, 1);
            }

            $('.week-picker').datepicker({
                showOtherMonths: true,
                firstDay: 1,
                showWeek: true,
                selectOtherMonths: true,
                onSelect: function (dateText, inst) {
                    var date = $(this).datepicker('getDate');
                    startDate = new Date(date.getFullYear(), date.getMonth(), date.getDate() - date.getDay() + 1);
                    endDate = new Date(date.getFullYear(), date.getMonth(), date.getDate() - date.getDay() + 4);
                    var dateFormat = inst.settings.dateFormat || $.datepicker._defaults.dateFormat;
                    $('#startDate').text($.datepicker.formatDate(dateFormat, startDate, inst.settings));
                    $('#endDate').text($.datepicker.formatDate(dateFormat, endDate, inst.settings));

                    selectCurrentWeek();
                },
                beforeShowDay: $.datepicker.noWeekends, function(date) {
                    var cssClass = '';
                    if (date >= startDate && date <= endDate)
                        cssClass = 'ui-datepicker-current-day';
                    return [true, cssClass];
                },
                onChangeMonthYear: function (year, month, inst) {
                    selectCurrentWeek();
                },
                onClose: function (dateText, inst) {
                    var date = $(this).datepicker('getDate');
                    startDate = new Date(date.getFullYear(), date.getMonth(), date.getDate() - date.getDay() + 1);
                    endDate = new Date(date.getFullYear(), date.getMonth(), date.getDate() - date.getDay() + 5);
                    var dateFormat = inst.settings.dateFormat || $.datepicker._defaults.dateFormat;

                    var sdmonth = startDate.getMonth() + 1;
                    var sdday = startDate.getDate();

                    var edmonth = endDate.getMonth() + 1;
                    var edday = endDate.getDate();

                    var sdoutput = (sdday < 10 ? '0' : '') + sdday + '-' +
                        (sdmonth < 10 ? '0' : '') + sdmonth + '-' +
                        startDate.getFullYear();

                    var edoutput = (edday < 10 ? '0' : '') + edday + '-' +
                        (edmonth < 10 ? '0' : '') + edmonth + '-' +
                        endDate.getFullYear();

                    var wk = $.datepicker.iso8601Week(new Date(dateText));
                    if (parseInt(wk) < 10) {
                        wk = "0" + wk;
                    }

                    if (isNaN(wk)) {
                        $(this).val("");
                    } else {
                        $(this).val(sdoutput + " - " + edoutput);
                    }

                }
            });

            $('.week-picker .ui-datepicker-calendar tr').on('mousemove', function () { $(this).find('td a').addClass('ui-state-hover'); });
            $('.week-picker .ui-datepicker-calendar tr').on('mouseleave', function () { $(this).find('td a').removeClass('ui-state-hover'); });
        });
    </script>
}
<div class="panel panel-default">
    <div class="panel-heading">
        <h2 style="color:#3277b3">Vælg uge</h2>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("GetWeeklySales", "Sale", FormMethod.Get))
        {
            <div class="row">
                
                <div class="col-md-6 col-sm-6">
                    <label>Uge: </label>
                    @Html.TextBoxFor(m => m.FullDate, new { @class = "week-picker" })
                    <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-folder-open"></span>&nbsp;Se Salg</button>

                </div>
                <div class="col-md-6 col-sm-6">
                    <button type="button" class="btn btn-warning" onclick="location.href='@Url.Action("GetMonthlySales", "Sale")'" style="float:right; overflow:auto"><span class="glyphicon glyphicon-folder-open"></span>&nbsp;Se Månedlige Salg</button>
                    <button type="button" class="btn btn-warning" onclick="location.href='@Url.Action("GetDailySales", "Sale")'" style="float:right;  margin-right:1%;"><span class="glyphicon glyphicon-folder-open"></span>&nbsp;Se Daglige Salg</button>
                </div>
            </div>
        }

    </div>
</div>

<div class="panel panel-primary">
    <div class="panel panel-heading" style="text-align:center"><h4 style="color:#ffffff; font-weight:bold">@Model.StartDate - @Model.EndDate</h4></div>

    <div class="form-group">
            <img src="@Url.Action("WeeklyCharterColumn", new { startDate = Model.StartDate, endDate = Model.EndDate })" alt="Chart" />

            <img style="float:right" src="@Url.Action("WeeklyCharterPie", new { startDate = Model.StartDate, endDate = Model.EndDate })" alt="Chart" />
        </div>

    <table class="table table-hover custab" style="background-color:white">
        <thead>
            <tr>
                <th style="color:#428bca">Produkt</th>
                <th style="color:#428bca">Pris pr. produkt</th>
                <th style="color:#428bca">Total solgt</th>
                <th style="color:#428bca">Samlede indtægter</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.CountOfProducts)
            {
                <tr>
                    <td>@item.product.Title</td>
                    <td>@item.product.Price kr.</td>
                    <td>@item.NumberOfProduct</td>
                    <td>@item.TotalPrice kr.</td>
                </tr>

            }
            <tr>
                <td><b style="color:#3277b3">Total: </b></td>
                <td></td>
                <td><b style="color:#3277b3">@Model.TotalProduct</b></td>
                <td><b style="color:#3277b3">@Model.Total kr.</b></td>
            </tr>
        </tbody>
    </table>

</div>